title: <p align="center"> Abhinav Aggarwal </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  
  <br>   
I am working on obd and error handler
  </p>



theme: jekyll-theme-minimal
