title: <p align="center"> Abhinav Aggarwal </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a>
  
  <br>   
  I'm working on OBD Diagnostic and error handler
  <br>
  </p>



theme: jekyll-theme-minimal
